# Generated by Django 5.0.14 on 2026-02-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated hospital (required for hospital_admin and doctor roles)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["hospital"], name="users_hospita_aabe15_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
    ]
