# Generated by Django 5.0.14 on 2026-02-07 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Primary diagnosis")),
                (
                    "diagnosis_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="ICD codes if applicable"
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("history_of_present_illness", models.TextField(blank=True)),
                ("examination_findings", models.TextField(blank=True)),
                ("prescription", models.TextField(blank=True)),
                (
                    "prescription_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured prescription: [{medicine, dosage, frequency, duration}]",
                    ),
                ),
                ("doctor_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records",
            },
        ),
    ]
