# Generated by Django 5.0.14 on 2026-02-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="diseases_treated",
            field=models.ManyToManyField(
                blank=True,
                help_text="Diseases/conditions treated at this hospital",
                related_name="hospitals",
                to="hospitals.disease",
            ),
        ),
    ]
