# Generated by Django 5.0.14 on 2026-02-07 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="hospitals.department",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="hospitals.specialization",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availabilityslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="doctors.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="specificdateavailability",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specific_availabilities",
                to="doctors.doctorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["hospital"], name="doctor_prof_hospita_13256f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["department"], name="doctor_prof_departm_1f511f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorprofile",
            index=models.Index(
                fields=["specialization"], name="doctor_prof_special_4364c6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilityslot",
            unique_together={("doctor", "day_of_week", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="specificdateavailability",
            unique_together={("doctor", "date", "start_time")},
        ),
    ]
