# Generated by Django 5.0.14 on 2026-02-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("hospitals", "0002_hospital_diseases_treated"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="diseases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Diseases/conditions this doctor specializes in treating",
                related_name="doctors",
                to="hospitals.disease",
            ),
        ),
    ]
